gigya.global:
  type: mapping
  label: 'Gigya global YML settings'
  mapping:
    langcode:
      type: text
      label: 'Language code'
    gigya:
      type: text
      label: 'Gigya'
    _core:
      type: text
      label: 'Core'
gigya.settings:
  type: mapping
  label: 'Gigya credentials settings'
  mapping:
    gigya_api_key:
      type: text
      label: 'Gigya Api Key'
    gigya_application_key:
      type: text
      label: 'Gigya Application Key'
    gigya_application_secret_key:
      type: text
      label: 'Gigya Application Secret Key'
    data_center:
      type: text
      label: 'Data Center'