gigya.global:
  type: config_object
  label: Gigya global settings
  mapping:
    gigya:
      type: mapping
      mapping:
        language:
          type: string
        languageFallback:
          type: string
        keyPath:
          type: string
        gigyaDebugMode:
          type: boolean
        globalParameters:
          type: mapping
          mapping:
            bypassCookiePolicy:
              type: string
            enabledProviders:
              type: string
            sessionExpiration:
              type: integer
        enableRaaS:
          type: boolean
        fieldMapping:
          type: mapping

gigya.settings:
  type: config_object
  label: 'Gigya credentials settings'
  mapping:
    gigya:
      type: mapping
      mapping:
        gigya_api_key:
          type: text
          label: 'Gigya Api Key'
        gigya_application_key:
          type: text
          label: 'Gigya Application Key'
        gigya_auth_mode:
          type: string
          label: 'Gigya authentication mode'
        gigya_application_secret_key:
          type: text
          label: 'Gigya Application Secret Key'
        gigya_rsa_private_key:
          type: text
          label: 'Gigya RSA private key'
        gigya_rsa_public_key:
          type: text
          label: 'Gigya RSA public key'
        gigya_data_center:
          type: text
          label: 'Data Center'
