gigya_raas.settings:
  type: mapping
  label: 'Gigya RaaS Session Settings'
  mapping:
    gigya_raas_session_type:
      type: text
      label: 'Session Type'
    gigya_raas_session_time:
      type: integer
      label: 'Session Duration'