gigya.settings:
  type: mapping
  label: 'Gigya Socialize keys settings'
  mapping:
    api_key:
      type: text
      label: 'Gigya API Key'
    secret_key:
      type: text
      label: 'Gigya Secret Key'
    data_center:
      type: text
      label: 'Data Center'